// Copyright (C) Microsoft Corporation. All rights reserved.
define("Build/Extensions/GitHubEnterprise/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.AcceptUntrustedSSL = "Accept untrusted SSL certificates";
    exports.Authorize = "Authorize";
    exports.AuthorizeWithPAT = "Authorize with a personal access token";
    exports.Cancel = "Cancel";
    exports.ConnectionNameFormat = "{0} ({1})";
    exports.ConnectToGitHub = "Connect to GitHub Enterprise Server";
    exports.ConnectToGitHubTitle = "Connect to your GitHub Enterprise Server";
    exports.Create = "Create";
    exports.CreateNewConnection = "Or, create a new connection";
    exports.Creating = "Creating";
    exports.GitHubEnterprise = "GitHub Enterprise Server";
    exports.GitHubEnterpriseTagLine = "The self-hosted version of GitHub Enterprise";
    exports.GrantPermission = "Grant Azure Pipelines permission to access your {0} repositories to continue.";
    exports.ImageOfNoConnections = "Image of no existing connections";
    exports.NewConnection = "New connection";
    exports.NewConnectionPanelTitle = "New GitHub Enterprise Server connection";
    exports.PersonalAccessToken = "Personal access token";
    exports.PersonalAccessTokenDescription = "Your token must have the following scopes:";
    exports.PersonalAccessTokenLabel = "Personal access token";
    exports.PersonalAccessTokenScopes = "repo, read:user, user:email, admin:repo_hook";
    exports.SelectRepositoryTitle = "Select a repository";
    exports.ServerUrlLabel = "GitHub Enterprise Server URL";
    exports.ServerUrlPlaceholder = "For example, https://github.fabrikam.com";
    exports.Unknown = "Unknown";
    exports.UseExistingConnection = "Use an existing connection";
    exports.UsernamePassword = "Username and password";
});