// Copyright (C) Microsoft Corporation. All rights reserved.
define("Wiki/Overview/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.CopyPagePathMenuItemText = "Copy page path";
    exports.IsAFolder = "\u0027{0}\u0027 is a folder";
    exports.PrintPageMenuItemText = "Print";
    exports.EditPageMenuItemText = "Edit";
    exports.EditInReposMenuItemText = "Edit in Repos";
    exports.LinkWitMenuItemText = "Link work items";
    exports.MovePageDefaultComment = "Page \u0027{0}\u0027 moved from parent \u0027{1}\u0027 to \u0027{2}\u0027";
    exports.MovePageMenuItem = "Move page";
    exports.TreeAllPagesHeader = "Pages";
    exports.PageRevisionsMenuItemText = "View revisions";
    exports.NewPageActionButton = "New page";
    exports.ShowLessNavPane = "Show less information";
    exports.ShowMoreNavPane = "Show more information";
    exports.FilterTreeWatermarkText = "Filter pages by title";
    exports.DeletePageText = "Delete";
    exports.OpenInNewTabText = "Open in new tab";
    exports.SetAsHomePage = "Set as wiki Homepage";
    exports.LearnMoreToastCTA = "Learn more";
    exports.AddSubPage = "Add sub-page";
    exports.FilteredTree_NoResultsFound = "No results found";
    exports.MovePage_BrokenLinkFixing_Title = "Move page";
    exports.MovePageDialog_BrokenLinkFixing_MoveButtonText = "Move";
    exports.MoveWithoutFixingButtonText = "Move without fixing";
    exports.MovePage_BrokenLinkFixing_FixAndMoveButtonText = "Fix and move";
    exports.MovePage_BrokenLinkFixing_SuccessMessage = "Page moved successfully from \u0027{0}\u0027 to \u0027{1}\u0027.";
    exports.MovePage_BrokenLinkFixing_AutoFix = "Moving page \u0027{0}\u0027 to \u0027{1}\u0027.";
    exports.PageNotFound = "Page does not exist";
    exports.ViewShortcutGroupHeading = "Wiki";
    exports.TreeShortcut_MoveUp = "Move page up the order";
    exports.TreeShortcut_MoveDown = "Move page down the order";
    exports.WindowTitleForNewPage = "New page - Wiki";
    exports.NonConformantPageError = "Could not the load page. Either the page\u0027s title or any of its ancestor page\u0027s title does not conform to Wiki standards.";
    exports.NonConformantPageLearnMoreText = "Learn more";
    exports.NonConformancePageLearnMoreLink = "https://go.microsoft.com/fwlink/?linkid=2087602";
    exports.PageShortcut_Add = "Add new page";
    exports.PageShortcut_AddSubPage = "Create new sub-page";
    exports.PageShortcut_Edit = "Edit page";
    exports.PageShortcut_Print = "Print current page";
    exports.IncludesPrimaryMessage = "Reuse content, reduce redundancy.";
    exports.IncludesSecondaryMessage = "Templates are reusable markdown pages that can be used within multiple wiki pages.";
    exports.AddIncludeText = "Add template";
    exports.CreatedAndEmbeddedWit = "Created and embedded {0} with id {1}";
    exports.EmbedWitFailed = "{0} with id {1} was created but failed to embed. You can manually embed it in the page.";
});