// Copyright (C) Microsoft Corporation. All rights reserved.
define("DistributedTaskUI/SecurityComponent/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.OpenAccessDialogTitle = "Confirm open access";
    exports.OpenAccessDialogCancelButton = "Cancel";
    exports.OpenAccessDialogConfirmButton = "Open access";
    exports.OpenAccessDialogWarning = "Are you sure you want to continue?";
    exports.OpenAccessDialogMessage = "This will allow all pipelines in the project to use this resource";
    exports.RestrictAccessPanelTitle = "Granting permissions";
    exports.RestrictAccessPanelConfirmButton = "Got it";
    exports.RestrictAccessPanelContecntLine1 = "For continuity, the following pipelines will automatically be granted permissions.";
    exports.RestrictAccessPanelContecntLine2 = "You may remove their permissions later at any time.";
    exports.PipelineString = "Pipeline";
    exports.PipelinePermissionsTitle = "Pipeline permissions";
    exports.PipelinePermissionsDescription = "The pipelines below are allowed to use this resource";
    exports.OpenAccessMenuItem = "Open access";
    exports.ViewOptionsTooltip = "More actions";
    exports.NoRestrictionsCardTitle = "No restrictions";
    exports.NoRestrictionsCardContent = "Any pipeline may use this resource";
    exports.RestrictAccessButtonText = "Restrict permission";
    exports.NoAuthorizedPipelinesCardTitle = "No permitted pipelines";
    exports.NoAuthorizedPipelinesCardContent = "This resource cannot be used until at least one pipeline has permission";
    exports.LearnMoreText = "Learn more";
    exports.RecentText = "Recent";
    exports.AllText = "All";
    exports.RevokeAccessTooltip = "Revoke access";
    exports.AuthorizePipelinesTooltip = "Add pipeline";
    exports.AccessAssigned = "Assigned";
    exports.AccessInherited = "Inherited";
    exports.AddUsersDialogTitle = "Add User";
    exports.AddRoleInputField = "Role";
    exports.AddButtonText = "Add";
    exports.CloseButtonLabelText = "Close";
    exports.UndoButtonText = "Undo";
    exports.SaveButtonText = "Save";
    exports.AddUserInputField = "User or group";
    exports.CannotEditRolesMessage = "You do not have permission to edit roles for this resource.";
    exports.InheritanceButtonText = "Inheritance";
    exports.InheritenceOnButtonText = "On";
    exports.InheritenceOffButtonText = "Off";
    exports.InitialDataLoadError = "Failed to load the authorization details.";
    exports.UpdateAuthorizationError = "Updating pipelines authorization failed.";
});