// Copyright (C) Microsoft Corporation. All rights reserved.
define("Wit/WorkItemView/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.Feedback_DialogTitle = "Send us feedback";
    exports.Feedback_PrivacyLabel = "Your privacy is important to us.";
    exports.Feedback_PrivacyUrl = "https://go.microsoft.com/fwlink/?LinkId=264782";
    exports.Feedback_IntroText = "Tell us what you think about the new work item. What is working well? How can we improve the experience?";
    exports.Feedback_ContactMeLabel = "Microsoft can contact me about my feedback.";
    exports.Feedback_FeedbackSubmitted = "Thank you for taking the time to provide feedback on your experience.";
    exports.Add = "Add";
    exports.Attachments = "Attachments";
    exports.CannotLoadWorkItem = "Work item {0} does not exist, or you don\u0027t have permission to read it.";
    exports.Cancel = "Cancel";
    exports.CollapsibleGroupCollapse = "Collapse {0}";
    exports.CollapsibleGroupExpand = "Expand {0}";
    exports.Create = "Create";
    exports.CreateWorkItemShortcutDescription = "Create work item";
    exports.FailedToUploadAttachment = "Failed to upload attachment.";
    exports.SendFeedback = "Send us feedback";
    exports.Follow = "Follow";
    exports.Leave = "Leave";
    exports.Loading = "Loading...";
    exports.New = "New";
    exports.Page_AllFields = "All fields";
    exports.Page_Overview = "Overview";
    exports.PreviewOpenInOldForm = "Open in old form";
    exports.Save = "Save";
    exports.SaveWorkItemShortcutDescription = "Your changes are auto-saved";
    exports.ServerError = "Server Error";
    exports.Share = "Share";
    exports.ShowMore = "Show More";
    exports.Stay = "Stay";
    exports.Tags = "Tags";
    exports.TogglePreview = "Toggle Preview";
    exports.Unassigned = "Unassigned";
    exports.UnexpectedError = "An unexpected error occurred while loading the workItem.";
    exports.Unfollow = "Unfollow";
    exports.UnsavedChangesMessage = "Changes you made may not be saved.";
    exports.UnsavedChangesTitle = "Are you sure you want to leave the page?";
    exports.WorkItemSaveError = "Your changes could not be saved.";
    exports.WorkItemShortcutGroupName = "Work item";
    exports.Feed_Filter = "Important activity";
    exports.InitializeNewWorkItemError = "Unable to initialize a new work item";
});