// Copyright (C) Microsoft Corporation. All rights reserved.
define("VC/Views/Branches/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.BranchesHeaderTitle = "Branches";
    exports.CreateNewBranch = "New branch";
    exports.AllBranches = "All";
    exports.MyBranches = "Mine";
    exports.StaleBranches = "Stale";
    exports.SearchAllBranches = "Search all branches";
    exports.ColumnAuthorHeader = "Author";
    exports.ColumnBranchHeader = "Branch";
    exports.ColumnBuildHeader = "Build";
    exports.ColumnCommitHeader = "Commit";
    exports.ColumnAuthoredDateHeader = "Authored Date";
    exports.ColumnBehidAheadHeader = "Behind | Ahead";
    exports.ColumnPullRequestHeader = "Pull Request";
    exports.BranchesListDescription = "List of branches";
    exports.DefaultBranch = "Default";
    exports.CompareBranch = "Compare";
    exports.CopySHA = "Copy full SHA1 to clipboard";
    exports.AddToFavorites = "Add to favorites";
    exports.RemoveFromFavorites = "Remove from favorites";
    exports.DeleteBranch = "Delete branch";
    exports.NewPullRequest = "New pull request";
    exports.PullRequestWithId = "Pull Request {0}: {1} {2} into {3}";
    exports.LockedBy = "Locked by {0}";
    exports.ShowingMatches = "Showing {0} branch(es) that matches: {1}.";
    exports.LockBranch = "Lock";
    exports.UnlockBranch = "Unlock";
});