// Copyright (C) Microsoft Corporation. All rights reserved.
define("Test/TestResultsGridToolbar/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.Owner = "Owner";
    exports.TestFileText = "Test file";
    exports.RequirementText = "Requirement";
    exports.GroupByText = "Group by";
    exports.NoneText = "None";
    exports.PriorityText = "Priority";
    exports.TestSuiteText = "Test suite";
    exports.TestRunText = "Test run";
    exports.FilterByTestName = "Filter by test or run name";
    exports.FilterNoOwner = "No owners available";
    exports.FilterNoTestFile = "No test files available";
    exports.Outcome = "Outcome";
    exports.HideFilterBarTitle = "Hide filter bar";
    exports.ShowFilterBarTitle = "Show filter bar";
    exports.ColumnOptionsTitle = "Column Options";
    exports.OpenColumnOptionPanel = "Open column options panel";
    exports.ViewMoreTests = "View more tests";
    exports.NoConfigInfoMessage = "Get fully-formed test reporting by configuring the reporter for your runner.";
    exports.LearnMoreText = "Learn more.";
    exports.FilterTagsText = "Tags";
    exports.FilterNoTags = "No tags available";
    exports.FilterStagesText = "Stages";
    exports.FilterNoStages = "No stages available";
    exports.FlakyText = "Flaky";
    exports.UnFlakyTest = "UnFlaky";
    exports.GroupByFormat = "Group by: {0}";
});