// Copyright (C) Microsoft Corporation. All rights reserved.
define("Wiki/Editor/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.EditorTextArea_AriaLabel = "Wiki page content. This field supports markdown.";
    exports.SaveButton_Label = "Save";
    exports.SaveDropdown_Label = "More save options";
    exports.CloseButton_Label = "Close";
    exports.PageName_PlaceHolder = "Untitled";
    exports.PageName_Label = "Page title";
    exports.ViewOptions_Label = "View options";
    exports.EditAndPreview_Label = "Edit and preview";
    exports.EditOnly_Label = "Edit only";
    exports.PreviewOnly_Label = "Preview only";
    exports.Attachment_MultipleNotSupportedFileTypes = "The file types {0} and {1} are not supported.";
    exports.Attachment_NotSupportedFileType = "The file type {0} is not supported.";
    exports.Attachment_FileSizeExceeded = "Attachment size must be less than {0} MB. The supported limit is exceeded for: {1}";
    exports.Attachment_UnSupportedCharactersInName = "Attachment name with the characters ({0}) are not supported. There are unsupported charcters in ";
    exports.UnsavedChanges_DialogTitle = "Unsaved changes";
    exports.ContinueEditing_Label = "Continue editing";
    exports.Discard_Label = "Discard";
    exports.DefaultFileDropText = "Drop files here";
    exports.UnsavedChanges_DialogMessage = "You have unsaved changes made to this page which will be lost if you navigate away. Would you like to continue editing?";
    exports.SaveRevisionMessage_Label = "Save with revision message";
    exports.PagePathTooLong = "The page path cannot exceed {0} characters.";
    exports.PageTitleEmpty = "The page title cannot be empty";
    exports.PageTitleInvalid = "The page title cannot begin or end with \".\"";
    exports.PageTitleInvalidCharacter = "The page title cannot contain / \\ #";
    exports.AddPageDefaultComment = "Added {0}";
    exports.EditPageDefaultComment = "Updated {0}";
    exports.RenamePageDefaultComment = "Renamed page \u0027{0}\u0027 to \u0027{1}\u0027";
    exports.EditAndRenamePageDefaultComment = "Updated content and renamed page \u0027{0}\u0027 to \u0027{1}\u0027";
    exports.SavePageDialog_SaveLabel = "Save";
    exports.SavePageDialog_CancelLabel = "Cancel";
    exports.SavePageDialog_Title = "Save page";
    exports.SavePageDialog_RenameInfoMessage = "Renaming this page may break any links to this page. You can fix the links manually.";
    exports.Attachment_SaveFailed = "Could not save the changes to the page since saving one or more attachments failed.";
    exports.ErrorMessage_PageConflict_Deleted = "Unable to update the page \u0027{0}\u0027 as it has been deleted or renamed. Copy your changes, refresh the browser to receive the latest pages and try your changes again.";
    exports.ErrorMessage_AncestorConflicts = "One or more pages in the hierarchy of the page \u0027{0}\u0027 does not exist anymore. Copy your changes if any, refresh the browser to receive the latest pages and try your changes again.";
    exports.ErrorMessage_PageConflict_Updated = "Unable to update the page \u0027{0}\u0027 as it was modified and you are editing an older version. Copy your changes, refresh the browser to receive the latest pages and try your changes again.";
    exports.ErrorMessage_FileSizePolicy = "Unable to save the page since the compressed size of one or more attachments exceeds the supported limit of 4 MB per file. You can remove such attachments and try saving again.";
    exports.ErrorMessage_PageConflict_AlreadyAdded = "Unable to add the page \u0027{0}\u0027 as another page with the same title already exists. Copy your changes, refresh the browser to receive the latest pages and try adding your content with a different page title.";
    exports.SavedPageMessage = "Saved page with message \u0027{0}\u0027";
    exports.DialogInfoFixAndRenameButtonText = "Fix and rename";
    exports.DialogInfoRenameWithoutFixingButtonText = "Rename without fixing";
    exports.PageRenameTitleMessage = "Renaming page \u0027{0}\u0027 to \u0027{1}\u0027.";
    exports.PageRenameSuccessMessage = "Page renamed successfully from \u0027{0}\u0027 to \u0027{1}\u0027";
    exports.PageContentSizeExceeded = "Cannot add more content. The page size is {0} MB which exceeds the supported size of {1} MB.";
    exports.ShortcutGroup = "Wiki edit";
    exports.ShortcutSaveChanges = "Save changes";
    exports.ShortcutSaveAndClose = "Save and Close";
    exports.ShortcutClose = "Close";
});