// Copyright (C) Microsoft Corporation. All rights reserved.
define("Test/TestResultsGrid/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.ResultGridTitle_Test = "Test";
    exports.QueryColumnNameDuration = "Duration";
    exports.ResultGridHeader_FailingRelease = "Failing release";
    exports.ResultGridHeader_FailingBuild = "Failing build";
    exports.ResultGridHeader_FailingSince = "Failing since";
    exports.ResultGridHeader_Owner = "Owner";
    exports.ResultGridHeader_DateStarted = "Date started";
    exports.ResultGridHeader_DateCompleted = "Date completed";
    exports.ResultGridHeader_Tags = "Tags";
    exports.LoadingMessage = "Loading...";
    exports.LoadingTestResultDetailsLabel = "Loading details...";
    exports.NewFailureIndicator = "New";
    exports.TestIndicatorSeparator = "|";
    exports.FlakyResultIndicator = "Flaky";
    exports.CurrentRelease = "Current release";
    exports.CurrentBuild = "Current build";
    exports.SubResultDisplayName = "Sub result {0}";
    exports.NoResultsForCurrentSetMessage = "No test results found for the specified filter(s) in the current set";
    exports.NoResultsMessage = "No test results found for the selected filter(s)";
    exports.NoResultsForCurrentSetSuggestionMessage = "Choose the next result set above to find test results relevant to you";
    exports.NoResultsSuggestionMessage = "Choose a different filter to view test results relevant to you";
    exports.NoFailedResultsMessage = "Hooray! There are no test failures.";
    exports.NoFailedResultsSuggestionMessage = "Change the test outcome filter to view tests relevant to you.";
    exports.TestResultsFilterClearedMessage = "Showing {0} of {1} test results.";
    exports.LoadMoreMessage = "Filtered {0} of {1} test results.";
    exports.ShowMoreTestResults = "Show more test results";
    exports.FetchingAll = "Fetching all test results";
    exports.FilterMoreTestResults = "Filter more test results";
    exports.DetailedListSortedAsc = "Test results grid sorted by {0} in ascending order.";
    exports.DetailedListSortedDesc = "Test results grid sorted by {0} in descending order.";
    exports.TagsList_AriaLabel = "Tags list";
    exports.SelectAll = "Select all";
    exports.SelectRow = "Select the row";
});