// Copyright (C) Microsoft Corporation. All rights reserved.
define("Analytics/Management/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.AnalyticsTitleText = "Analytics";
    exports.AnalyticsDescription = "Analytics is the future of reporting for Azure DevOps Server and allows teams to make data driven decisions through advanced widgets, Power BI integration through Analytics Views, in-product reports, and access to the OData endpoint. Enabling Analytics turns on these experiences. {0}.";
    exports.LearnMoreLinkText = "Click here to learn more about Analytics";
    exports.LearnMoreLinkUrl = "https://go.microsoft.com/fwlink/?linkid=2093060";
    exports.AnalyticsDataPreparing = "Data is being prepared";
    exports.AnalyticsDataPreparingDetails = "Analytics is getting your data ready for reporting in your colllection. This process may take some time. Please check back later.";
    exports.AnalyticsEnabled = "Enabled";
    exports.AnalyticsEnabledDetails = "Analytics is enabled for your collection.";
    exports.AnalyticsDisabling = "Disabling Analytics";
    exports.AnalyticsDisablingDetails = "Analytics is currently being disabled for your collection. This process may take some time. Please check back later.";
    exports.AnalyticsDisabled = "Not enabled";
    exports.AnalyticsDisabledDetails = "Analytics is not enabled for your collection.";
    exports.AnalyticsPaused = "Paused";
    exports.AnalyticsPausedDetails = "Analytics is paused for your collection.";
    exports.AnalyticsPausedSince = "Paused since: {0}";
    exports.PauseButtonText = "Pause Analytics";
    exports.DisableButtonText = "Disable Analytics";
    exports.EnableButtonText = "Enable Analytics";
    exports.ResumeButtonText = "Resume Analytics";
    exports.CancelButtonText = "Cancel";
    exports.PauseDialogTitle = "Pause Analytics";
    exports.PauseDialogBody = "Pausing Analytics will turn off Analytics experiences but will preserve your data. The data will be out of sync and when Analytics is resumed, the data will be brought up to date.";
    exports.ResumeFeaturesListDescription = "The following experiences will be reenabled:";
    exports.ResumeDialogTitle = "Resume Analytics";
    exports.ResumeDialogBody = "Resuming Analytics will turn on all Analytics experiences with data needing to be updated since it was paused.";
    exports.EnableFeaturesListDescription = "The following experiences will be reenabled:";
    exports.DisableDialogTitle = "Disable Analytics";
    exports.DisableDialogBody = "Disabling Analytics will turn off all Analytics experiences and also delete Analytics. Analytics data used for trending will be lost. If Analytics is reenabled, this data will need to be processed from scratch.";
    exports.PauseDisableFeaturesListDescription = "The following experiences will be turned off:";
    exports.AnalyticsExperienceListWidgetsItem = "Analytics widgets";
    exports.AnalyticsExperienceListInProductItem = "In-product experiences (test \u0026 pipeline failures reports)";
    exports.AnalyticsExperienceListPowerBiItem = "Power BI integration through Analytics Views";
    exports.AnalyticsExperienceListODataItem = "OData endpoint";
    exports.PauseDialogLinkText = "Click here to learn more about pausing Analytics";
    exports.DisableDialogLinkText = "Click here to learn more about disabling Analytics";
    exports.ResumeDialogLinkText = "Click here to learn more about resuming Analytics";
    exports.StateExplanationLinkUrl = "https://go.microsoft.com/fwlink/?linkid=2093061";
    exports.CollectionValidationInstructions = "Enter the name of the collection, {0}, to confirm:";
});