// Copyright (C) Microsoft Corporation. All rights reserved.
define("Environments/Providers/VirtualMachineGroups/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.AddTarget = "Add Target";
    exports.AgentPlatformLinux = "Linux";
    exports.AgentPlatformRedhat7 = "Red Hat Enterprise Linux 7.2+";
    exports.AgentPlatformUbuntu14 = "Ubuntu 14.04";
    exports.AgentPlatformUbuntu16 = "Ubuntu 16.04+";
    exports.AgentPlatformWindows = "Windows";
    exports.Copied = "Copied";
    exports.CopyPSScript = "Copy PowerShell registration script ";
    exports.CopyRegistrationScript = "Copy registraton script ";
    exports.CopyToClipboard = "Copy to clipboard";
    exports.GuidanceForInsufficientPermissions = "Insufficient permissions to register a target.";
    exports.GuidanceForRunPowerShellScript = "Run from an administrator PowerShell command prompt";
    exports.GuidanceForRunShellScript = "Run from an administrator command prompt";
    exports.GuidanceForUnsavedDeploymentGroup = "Save the deployment group prior to registering the machine";
    exports.GuidanceForUnsavedDeploymentPool = "Save the deployment pool prior to registering the machine.";
    exports.LatestDeployment = "Latest Deployment";
    exports.Loading = "Loading";
    exports.NameText = "Name";
    exports.NeverDeployed = "Never Deployed";
    exports.OperatingSystem = "Operating System";
    exports.PATCheckBoxLabel = "Use a personal access token in the script for authentication";
    exports.PSMinVersionCheck = "The minimum version of Windows PowerShell that is required by the script (3.0) does not match the currently running version of Windows PowerShell.";
    exports.RegisterMachine = "Register Target";
    exports.RegistrationScript = "Registration script";
    exports.RegistrationScriptPowerShell = "Registration script (PowerShell)";
    exports.RunCommandInAdministratorPowerShellPrompt = "Run command in an administrator PowerShell prompt";
    exports.SaveText = "Save";
    exports.ShowMore = "Show more";
    exports.SystemPreRequisitesLinkText = "System prerequisites";
    exports.TagsText = "Tags";
    exports.Targets = "Targets";
    exports.VirtualMachineResources = "Virtual Machine Resources";
    exports.VirtualMachinesText = "Virtual machines";
    exports.WorkloadsText = "Workloads";
});