// Copyright (C) Microsoft Corporation. All rights reserved.
define("Tfs/Platform/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.ManageUserSettings = "Manage the currently logged in user settings";
    exports.MoreMenu = "More ...";
    exports.Pin = "Pin";
    exports.RecentProjectTeams = "Recent project/teams";
    exports.Unpin = "Unpin";
    exports.UnpinnedItems = "Unpinned items";
    exports.DocumentTitle = "{0} - {1}";
    exports.ApplicationTitleHosted = "Azure DevOps Services";
    exports.ApplicationTitleOnPrem = "Azure DevOps Server";
    exports.DevSuite = "Dev Suite";
    exports.Favorites = "Favorites";
    exports.Create = "Create";
    exports.Help = "Help";
    exports.Settings = "Settings";
    exports.ProjectSettings = "Project settings";
    exports.ShowDetails = "Show more information";
    exports.HideDetails = "Show less information";
    exports.ShowFavorites = "Show favorites";
    exports.ShowCreate = "Show commonly created items";
    exports.ShowApplications = "Switch to another application";
    exports.ProjectsAndTeams = "Projects \u0026 teams";
    exports.HeaderProjectNameFormat = "{0} / {1}";
    exports.Navigation_Site = "Website";
    exports.Dashboards = "Dashboards";
    exports.Wiki = "Wiki";
    exports.More = "More";
    exports.BrandName = "Azure";
    exports.ProductName = "DevOps";
    exports.BrandWithProductName = "Azure DevOps";
    exports.SuiteNameOnPrem = "DevOps";
    exports.SuiteName = "VSTS";
    exports.MarketPlace = "Marketplace";
    exports.Overview = "Overview";
    exports.UnhandledErrorTitle = "An unexpected error has occurred within this region of the page.";
    exports.UnhandledErrorMessage = "You can try reloading this component or refreshing the entire page.";
    exports.RefreshPageText = "Refresh page";
    exports.ReloadComponentText = "Reload component";
    exports.ShowMoreInfoText = "Show more info";
    exports.SuiteLogoLabel = "Azure DevOps organization home page";
    exports.SuiteLogoLabelOnPrem = "Azure DevOps collection home page";
    exports.Error = "Error";
    exports.Stack = "Stack";
});