// Copyright (C) Microsoft Corporation. All rights reserved.
define("Test/TestResultWorkItems/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.AnnounceSelected = "Selected";
    exports.AnnounceDeselected = "Deselected";
    exports.AnnounceAssociationsDeleted = "{0} Associations Successfully Deleted";
    exports.UnableToDeleteAssociationText = "Unable to remove link to associated work item(s) : {0}";
    exports.CommaSeparator = ",";
    exports.TestPointGridColumnID = "ID";
    exports.WorkItemGridTitleColumnHeader = "Title";
    exports.ExploratorySessionGridHeader_State = "State";
    exports.AssignedTo = "Assigned To";
    exports.DateCreated = "Created Date";
    exports.LastUpdated = "Last updated";
    exports.BugsLabel = "Bugs ({0})";
    exports.ClearErrorMessage = "Clear error message";
    exports.BugsText = "Bugs";
    exports.SelectAll = "Select all";
    exports.SelectRow = "Select the row";
    exports.AnnounceSortedDesc = "Sorted by {0} in descending order";
    exports.AnnounceSortedAsc = "Sorted by {0} in ascending order";
    exports.OpenInNewTab = "Open in new tab";
    exports.RemoveLink = "Remove link";
    exports.DeleteRequirementConfirmationText = "Are you sure you want to delete this association?";
    exports.LoadingBugsMessage = "Loading bugs...";
    exports.CloseText = "Close";
    exports.OkText = "Ok";
    exports.CancelText = "Cancel";
    exports.ConfirmText = "Confirm";
    exports.AnnounceAttachmentsDeleted = "{0} Attachments Successfully Deleted";
    exports.RequirementsLabel = "Requirements ({0})";
    exports.LoadingRequirementsMessage = "Loading requirements...";
    exports.LoadingWorkItems = "Loading work items...";
    exports.NoWorkItemsMessage = "No work items available for selected item";
});