// Copyright (C) Microsoft Corporation. All rights reserved.
define("TFS/CreateProject/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.CreateProjectCancelButtonText = "Cancel";
    exports.CreateProjectCollectionNameContainerHeader = "Collection name";
    exports.CreateProjectCTAButtonText = "Create project";
    exports.CreateProjectWithCancelCTAButtonText = "Create";
    exports.CreateProjectDescriptionContainerHeader = "Description";
    exports.CreateProjectFormHeader = "Create new project";
    exports.CreateProjectNameContainerHeader = "Project name";
    exports.CreateProjectNameNotAvailableText = "The project \u0027{0}\u0027 already exists.";
    exports.CreateProjectProjectVisibilitySectionHeader = "Visibility";
    exports.CreateProjectOperationFailedErrorText = "Project creation operation failed. Please retry project creation.";
    exports.LoadingText = "Loading...";
    exports.CreateProjectAdvancedOptionsText = "Advanced";
    exports.CreateProjectCreateCTAButtonToolTip = "Create project";
    exports.CreatingProjectAnnouncementMessage = "Creating project";
    exports.ProjectDecriptionTextFieldAriaDescription = "Enter a brief description for your project. This field is optional.";
    exports.CreateProjectNameAriaDescription = "Enter a memorable name for your project.";
    exports.CreateProjectGenericServerErrorText = "We are having trouble loading the content.";
    exports.CollapsibleMessageHideDetails = "Hide details";
    exports.CollapsibleMessageShowDetails = "Show details";
    exports.CreateProjectUnauthorizedAccessText = "You do not have sufficient permissions to create a new project. Please contact the organization administrator for support.";
    exports.CreateProjectOperationFailedErrorTextOnPrem = "Project creation operation failed.";
    exports.RetrieveCreateProjectFailureTextAfterHere = "to download full logs.";
    exports.RetrieveCreateProjectFailureTextHere = "here";
    exports.RetrieveCreateProjectFailureTextPreHere = "Click";
    exports.CreateProjectCodeOfConductLink = "https://aka.ms/vstscodeofconduct";
    exports.CreateProjectCodeOfConductStatement = "By creating this project, you agree to the {0} {1}";
    exports.CreateProjectCodeOfConductText = "code of conduct";
    exports.CreateProjectDisabledProjectVisibilityTooltip = "Your organization doesn\u0027t allow {0} projects.";
    exports.CreateProjectPolicyMessage = "Public projects are disabled for your organization. You can turn on public visibility with {0}.";
    exports.CreateProjectPolicyLinkText = "organization policies";
    exports.CreateProjectInvalidVisibilityValue = "{0} is not a valid visibility value.";
    exports.CreateProjectMembersOfYourOrganizationText = "Members of your enterprise";
    exports.CreateProjectOrganizationVisibilityOptionDescription = "{0} can view the project.";
    exports.CreateProjectOrganizationVisibilityText = "Enterprise";
    exports.CreateProjectPrivateVisibilityOptionDescription = "Only people you give access to will be able to view this project.";
    exports.CreateProjectPrivateVisibilityText = "Private";
    exports.CreateProjectPublicVisibilityOptionDescription = "Anyone on the internet can view the project. Certain features like TFVC are not supported.";
    exports.CreateProjectPublicVisibilityText = "Public";
    exports.UnknownOperationStateErrorMessage = "Unknown operation state";
    exports.ProjectNameErrorMessage_EmptyName = "Project name cannot be empty";
    exports.ProjectNameErrorMessage_MaxLengthCrossed = "Project name can be a maximum of 64 characters";
    exports.ProjectNameErrorMessage_InvalidStartingChar = "Project name cannot start with \u0027.\u0027 or \u0027_\u0027";
    exports.ProjectNameErrorMessage_InvalidEndingChar = "Project name cannot end with \u0027.\u0027";
    exports.ProjectNameErrorMessage_InvalidChar = "Project name cannot contain \u0027{0}\u0027";
    exports.ProjectNameErrorMessage_ReservedNameNotAllowed = "\u0027{0}\u0027 is reserved. It cannot be used as project name.";
    exports.TryAgainButtonText = "Try again";
    exports.GoBackButtonText = "Go Back";
    exports.CreatingNewProjectMessage = "Your new project is being created right now...";
    exports.GenericErrorMessage = "Oops, something went wrong.";
    exports.DownloadLogsMessage = "Click {0} to download full logs.";
    exports.HereText = "here";
    exports.ReportingServiceWarningUrl = "https://go.microsoft.com/fwlink/?linkid=852483";
    exports.ReportingServiceWarningMessage = "Reports are not created automatically. {0} how you can create your reports afterwards.";
    exports.FindOutText = "Find out";
});