// Copyright (C) Microsoft Corporation. All rights reserved.
define("AuditPage/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.Header = "Auditing";
    exports.TableColumnActor = "Actor";
    exports.TableColumnTimestamp = "Timestamp";
    exports.TableColumnScope = "Scope";
    exports.TableColumnArea = "Area";
    exports.TableColumnCategory = "Category";
    exports.TableColumnDetails = "Details";
    exports.FilterContainer_DateTimeRange = "Date Time Range";
    exports.AuditLogNoResultsPrimary = "Nothing to see here";
    exports.AuditLogNoResultsSecondary = "Looks like nothing turned up. Try changing your filters to return more results.";
    exports.MoreInformation = "More information";
    exports.DetailsHeading = "Details";
    exports.ChangeColumnHeader = "Change";
    exports.NamespaceColumnHeader = "Namespace";
    exports.PermissionsColumnHeader = "Permissions";
    exports.SubjectColumnHeader = "Subject";
    exports.PropertyColumnHeader = "Property";
    exports.ValueColumnHeader = "Value";
    exports.OldValueColumnHeader = "Old value";
    exports.DownloadButton = "Download";
    exports.CSV = "CSV";
    exports.JSON = "JSON";
    exports.Loading = "Loading...";
    exports.Loaded = "Loading completed.";
    exports.AccessTime = "Access Time";
    exports.RetryButton = "Retry";
    exports.CancelButton = "Cancel";
    exports.CloseDetailsPanelButton = "Close details panel";
    exports.StartBeforeEndValidationMessage = "An invalid time range was provided. Please ensure that your start time comes before the end time.";
    exports.ColumnSortedAscendingAnnouncment = "{0} column sorted ascending";
    exports.ColumnSortedDescendingAnnouncment = "{0} column sorted descending";
    exports.DateTimeFormatHelp = "Format: mm/dd/yyyy hh:mm AM/PM";
    exports.StartTimeAriaLabel = "Start time (hh:mm) AM/PM";
    exports.EndTimeAriaLabel = "End time (hh:mm) AM/PM";
});