// Copyright (C) Microsoft Corporation. All rights reserved.
define("Environments/EnvironmentDetails/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.AddResource = "Add resource";
    exports.Checks = "Checks";
    exports.Delete = "Delete";
    exports.DeleteDialogHeader = "Delete \u0027{0}\u0027?";
    exports.DeleteEnvironmentDialogText = "You will lose all the traceability associated with this environment. Are you sure you want to delete?";
    exports.EditButtonText = "Edit";
    exports.JobDetails = "{0} and {1} more";
    exports.Loading = "Loading...";
    exports.Pipeline = "Pipeline";
    exports.ResourceColumnName = "Name";
    exports.ResourceFilter = "Resource";
    exports.Run = "Run";
    exports.RunsJobsColumnName = "Jobs";
    exports.Security = "Security";
    exports.ShowMoreButtonText = "Show more";
    exports.ZeroDataDeploymentsPrimaryText = "You\u0027re almost done!";
    exports.ZeroDataDeploymentsSecondaryText = "Use in pipeline YAML to track deployments per resource.";
    exports.ZeroDataDeploymentsImageAltText = "Image of create first deployment";
    exports.ZeroDataResourcesPrimaryText = "Get started!";
    exports.ZeroDataResourcesSecondaryTextEnvironmentReady = "Your environment is ready to use in pipeline YAML ";
    exports.ZeroDataResourcesSecondaryTextAddResource = "To get full end to end traceability per resource";
    exports.ZeroDataResourcesImageAltText = "Image of create first resource";
    exports.DeploymentSucceeded = "Succeeded";
    exports.DeploymentFailed = "Failed";
    exports.SearchResourcesPlaceholder = "Filter by keywords";
    exports.ResourceStatusColumnName = "Status";
    exports.ResourceTypeColumnName = "Resource type";
    exports.KubernetesResource = "Kubernetes";
    exports.VirtualMachineResource = "Virtual machine";
    exports.NeverDeployed = "Never deployed";
    exports.ResourceLatesJobColumnName = "Latest job";
    exports.lastDeploymentStatusMessage = "#{0} on {1}";
    exports.DeploymentsSecondaryText = "#{0} on {1}";
    exports.NoneResource = "None";
    exports.NoResultsFound = "No results found";
    exports.ResourceDeletedToastMessage = "Resource \u0027{0}\u0027 has been deleted";
});