// Copyright (C) Microsoft Corporation. All rights reserved.
define("TFS/Views/ProjectOverviewPage/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.ProjectInformationRegion_Label = "Project Information";
    exports.VisibilityTag_VisibilityValueInvalid = "{0} is not a valid visibility value.";
    exports.VisibilityTag_PrivateProject_Tooltip_Text = "Shared with members of the project";
    exports.VisibilityTag_OrgVisibleProject_Tooltip_Text = "Shared with people in your enterprise";
    exports.VisibilityTag_PublicProject_Tooltip_Text = "Anyone on the internet can view";
    exports.InviteButtonText = "Invite";
    exports.Loading_Label = "Loading...";
    exports.ZeroDayCardAriaLabel = "Get Started";
    exports.ProjectNameEditButtonAriaLabel = "Edit project name";
    exports.AboutProjectTitle = "About this project";
    exports.AboutProjectCardReadMoreLinkText = "Read more";
    exports.AboutProjectDescriptionLengthExceededMessage = "The length of the description should be less than {0}, actual is {1}.";
    exports.AboutProjectPanelTagsHeading = "Tags";
    exports.AboutProjectPanelAboutSectionHeading = "About";
    exports.AboutProjectUpsellHeading = "Help others to get on board!";
    exports.AboutProjectUpsellMessage = "Describe your project and make it easier for other people to understand it.";
    exports.AboutProjectUpsellHeading_NoPermission = "This project has no description yet";
    exports.AboutProjectUpsellMessage_NoPermission = "Describing the project makes it easier for other people to understand it.";
    exports.AboutProjectUpsellButtonText = "Add Project Description";
    exports.ProjectMembers_ErrorLoadingMembers = "Failed to load project members. Refresh to try again.";
    exports.ProjectMembers_Title = "Members";
    exports.ProjectMembers_ImageOf = "Image of {0}";
    exports.ProjectStats = "Project stats";
    exports.AboutProjectChangesSavedMessage = "Changes have been saved successfully.";
    exports.Tag_ItemNameAriaLabel = "{0} Tag";
    exports.Tag_DeleteButtonAriaLabel = "Delete {0} Tag";
    exports.ProjectTags_AriaLabel = "Project Tags";
    exports.ProjectTags_MaxCountExceeded = "Tags count exceeded allowed limit, only {0} tags are allowed.";
    exports.ProjectTags_MaxCountReached = "Tags count reached allowed limit, only {0} tags are allowed.";
    exports.ProjectTags_TagCharacterLimitExceeded = "Tag cannot be greater than {0} characters long.";
    exports.LastOneDay = "Last 1 day";
    exports.LastSevenDays = "Last 7 days";
    exports.LastThirtyDays = "Last 30 days";
    exports.StatsDropdownAriaLabel = "Day range picker";
    exports.StatsUpsellMessage = "No stats are available at this moment";
    exports.StatsUpsellHelpText = "Setup a service to see project activity.";
    exports.ProjectOverviewDayZero_Title = "Welcome to the project!";
    exports.ProjectOverviewDayZero_SubTitle_TwoOrMoreServices = "What service would you like to start with?";
    exports.ProjectOverviewDayZero_SubTitle_OneService = "Get started with your service";
    exports.ProjectOverviewDayZero_OrManageYourServiceText = "or manage your services";
    exports.ProjectOverviewDayZero_ManageYourServiceText = "Manage your services";
    exports.AboutProjectEditButtonAriaLabel = "Edit project information";
});