// Copyright (C) Microsoft Corporation. All rights reserved.
define("TFS/FeatureManagement/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.CancelButtonText = "Cancel";
    exports.CloseButtonText = "Close";
    exports.Loading = "Loading...";
    exports.ManageFeaturesOnLabel = "On";
    exports.ManageFeaturesOffLabel = "Off";
    exports.ToggleFeatureOnAriaLabelFormat = "{0}: on. Press enter to turn the feature off.";
    exports.ToggleFeatureOffAriaLabelFormat = "{0}: off. Press enter to turn the feature on.";
    exports.FeatureLearnMoreAriaLabel = "Learn more about feature: {0}";
    exports.LearnMore = "Learn more";
    exports.TurnOffFeatureDialogLabel = "How can we make this feature better?";
    exports.TurnOnFeatureDialogTitleFormat = "Turn on {0}?";
    exports.TurnOffFeatureDialogTitleFormat = "Turn off {0}?";
    exports.TurnOnFeatureButtonText = "Turn on";
    exports.TurnOffFeatureButtonText = "Turn off";
    exports.ManageFeaturesHeader = "Preview features";
    exports.ManageFeaturesHeaderOnPrem = "Manage features";
    exports.ManageFeaturesSubHeading = "The following preview features are available for your evaluation. Help us make them better!";
    exports.ManageFeaturesSubHeadingOnPrem = "The following features are optional and can be turned on or off.";
    exports.FeatureScope = "Feature scope";
    exports.NoFeatureScopeWritePermission = "You don\u0027t have permission to manage these features.";
    exports.NoFeaturesAvailable = "No features are available to manage.";
    exports.DevModeFeaturesHeaderTooltip = "This section lists all features and does not appear in retail builds.";
    exports.DevModeFeaturesHeader = "Experimental [Debug build only].";
    exports.DevModeEnableAllLabel = "Feeling lucky?";
    exports.DevModeEnableAllLinkText = "Enable all features";
    exports.ManageFeaturesScopeAccount = "for this organization [{0}]";
    exports.ManageFeaturesScopeCollection = "for this collection [{0}]";
    exports.ManageFeaturesScopeMe = "for me [{0}]";
    exports.ManageFeaturesScopeProject = "for this project [{0}]";
    exports.ManageFeaturesScopeTeam = "for this team [{0}]";
    exports.ToggleFeatureForAccountWarning = "This will affect all users in your organization.";
    exports.ToggleFeatureForCollectionWarning = "This will affect all users in your collection.";
    exports.ToggleFeatureForProjectWarning = "This will affect all users in your project.";
    exports.ToggleFeatureForTeamWarning = "This will affect all users in your team.";
    exports.FeatureBannerDismissButton = "Not now";
    exports.FeatureBannerNameFormat = "{0}:";
    exports.FeatureBannerTryItButton = "Try it!";
    exports.FeatureDismissedCalloutBody = "You can turn on this and other features in {0} under your profile menu.";
    exports.FeatureDismissedCalloutHeader = "No problem. If you change your mind...";
    exports.FeatureEnabledCalloutBody = "You can turn off this feature by going to {0} under your profile menu.";
    exports.PreviewFeaturesMenuHosted = "Preview features";
    exports.PreviewFeaturesMenuOnPrem = "Manage features";
    exports.FeatureEnabledCalloutHeader = "{0} is now on";
    exports.FilterFeatures = "Filter Features";
});