// Copyright (C) Microsoft Corporation. All rights reserved.
define("TFS/Admin/Views/ProfileSettings/SSHPublicKeysView/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.NewKey = "New Key";
    exports.SSHPublicKeysTitle = "SSH Public Keys";
    exports.NoResultsFoundText = "No SSH public keys have been added";
    exports.AddSSHKeyPanelTitle = "Add New SSH Key";
    exports.NoSSHKeysAvailableMessage = "There are no SSH public keys added to your account on this organization.";
    exports.HowToGenerateNewSSHPublicKey = "https://aka.ms/azure-devops-sshkeys";
    exports.ConnectToYourGitRepos = "https://aka.ms/azure-devops-sshkeys";
    exports.Fingerprint = "Fingerprint";
    exports.DateAdded = "Date Added";
    exports.RemoveSSHPublicKey = "Remove SSH Key";
    exports.DateValidUntil = "Expiration Date";
    exports.Cancel = "Cancel";
    exports.Create = "Create";
    exports.Remove = "Remove";
    exports.Delete = "Delete";
    exports.CloseBtn = "Close";
    exports.Add = "Add";
    exports.AddNewSSHPublicKeys = "Add New SSH Public Keys";
    exports.SecondaryAriaText = "Visit the documentation to learn how to generate your first SSH Key and select New Key to add it to your account.";
    exports.SecondaryText = "Visit the {0} to learn how to generate your first SSH Key and select New Key to add it to your account.";
    exports.SecondaryTextDocumentation = "documentation";
    exports.Name = "Name";
    exports.SSHKeyDataTitle = "SSH Key Data";
    exports.KeyData = "Key Data";
    exports.ServerMD5FingerprintTitle = "Server MD5 Fingerprint ";
    exports.ServerMD5FingerprintValue = "bc:dc:10:5c:1a:48:a7:c5:16:70:43:72:46:a6:2c:37 (RSA)";
    exports.ServerSHA256FingerprintTitle = "Server SHA256 Fingerprint ";
    exports.ServerSHA256FingerprintValue = "YGzJgZudZVkYdnmgPuLFFgWE6CLA+cTuTcm+Jbs7g0Q (RSA)";
    exports.ServerInfo = "Compare the server fingerprint when you connect via Git to ensure you\u0027ve connected to Azure DevOps. The fingerprint should match one of the following:";
    exports.RemoveKeyTitle = "Remove public key";
    exports.RemoveKeyDialog = "Are you sure you want to remove {0} public key?";
    exports.RemoveKeyMessage = "This action will remove the key from your Azure DevOps organization and account, but it will not delete it from your console. {0}.";
    exports.LearnMoreAboutSSHKeys = "Learn more about SSH Keys";
    exports.ErrorRemovingSSHKeyMessage = "We were unable to remove";
    exports.TryAgain = ". Please try again.";
    exports.ToastMessage = "{0} was successfully {1}.";
    exports.Added = "added";
    exports.Removed = "removed";
    exports.UnableToAddSSHKeyMessage = "Unable to add duplicate SSH Key";
    exports.FailedToAddSSHKeyConnectionMessage = "We failed to add the {0} Key to your account on this organization due to a connection error. Please try again.";
    exports.InvalidKeyBase64 = "Invalid key: Key must be Base64 encoded with OpenSSH format and RSA type. Valid keys will start with \"ssh-rsa\".";
    exports.DuplicateKey = "We failed to add the {0} key to your account on this organization. It may be a duplicate of another key. Please check the current list and try again.";
    exports.FailedToAddKeyGeneric = "An error occurred while adding the SSH public key. Please try again.";
    exports.FailedToDeleteKey = "An error occured while deleting {0}. Please try again.";
});