// Copyright (C) Microsoft Corporation. All rights reserved.
define("Tfs/Frame/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.AccessLevels = "Access levels";
    exports.CollectionSettings = "Collection Settings";
    exports.BrandName = "Azure";
    exports.Collections = "Collections";
    exports.Create = "Create";
    exports.Documentation = "Documentation";
    exports.GetHelp = "Get help";
    exports.ManageUserSettings = "Manage the currently logged in user settings";
    exports.Marketplace = "Marketplace";
    exports.MyOrgs = "My organizations";
    exports.MyWorkLabel = "My Work";
    exports.NewOrg = "New organization";
    exports.OrgSettings = "Organization settings";
    exports.ProjectSettings = "Project settings";
    exports.ProductName = "DevOps";
    exports.RelatedPages = "Related pages";
    exports.ShowLess = "Show less information";
    exports.ShowMore = "Show more information";
    exports.SignIn = "Sign in";
    exports.SuiteLogoLabel = "Azure DevOps organization home page";
    exports.SuiteLogoLabelOnPrem = "Azure DevOps collection home page";
    exports.WhatsNew = "What\u0027s new in DevOps";
    exports.MoreOrganizations = "{0} more organizations";
    exports.OneMoreOrganization = "1 more organization";
    exports.AzureDevOpsProfile = "User settings";
    exports.PreviewFeatures = "Preview features";
});