// Copyright (C) Microsoft Corporation. All rights reserved.
define("TFS/Admin/Views/ProfileSettings/AlternateCredentialsView/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.Description = "Description";
    exports.Edit = "Edit";
    exports.Add = "Add";
    exports.Delete = "Delete";
    exports.Cancel = "Cancel";
    exports.Save = "Save";
    exports.Active = "Active";
    exports.DeleteAltCredsText = "Delete Alternate Credentials";
    exports.Inactive = "Inactive";
    exports.AltCredsTitle = "Alternate Credentials";
    exports.AltCredsDescription = "Create an alternate user name and password to access your Git repository using alternate credentials. Unlike personal access tokens, this login doesn\u0027t expire and can\u0027t be scoped to limit access to your Azure DevOps Services data. Use alternate credentials as a last resort when you can\u0027t use personal access tokens or SSH keys.";
    exports.AltCredsDisabledTitle = "Alternate credentials have been disabled on this organization";
    exports.AltCredsDisabledMessage = "Personal access tokens are a more convenient and secure replacement for Alternate authentication credentials";
    exports.PrimaryLabel = "Primary";
    exports.SecondaryLabel = "Secondary";
    exports.SecondaryUsernameInput = "Secondary username input text field";
    exports.PasswordInputAriaText = "Password input text field";
    exports.ConfirmPasswordInputAriaText = "Confirm password input text field";
    exports.Username = "Username";
    exports.ConfirmPassword = "Confirm Password";
    exports.Password = "Password";
    exports.DeleteAltCredsMessage = "Are you sure you want to delete the alternate credentials on your account for this organization?";
    exports.ToastMessage = "{0} was successfully {1}";
    exports.Removed = "removed";
    exports.Saved = "saved";
    exports.PasswordRequirementsNotMet = "The password provided does not meet the minimum security requirements. The password must be between 8 and 32 letters in length and cannot be the word \"password\"";
    exports.FailedToSaveAlternateCredentials = "Failed to save alternate credentials, please try again";
    exports.FailedToDeleteAlternateCredentials = "Failed to delete alternate credentials, please try again";
    exports.UsernameValidationIssueOnlyCharsNums = "Username cannot start with a number and can only be letters and numbers";
    exports.UsernameLength = "Username must have a length greater than 3 letters";
    exports.PaswordLength = "Password must be between 8 and 32 letters";
    exports.PasswordRequirementsStrength = "Password must contain at least 1 lowercase character, 1 uppercase, 1 numerical character, and at least 1 special character !@#$%^.\u0026";
    exports.PasswordsDoNotMatch = "Password fields do not match";
    exports.PasswordCannotBePassword = "Password cannot be password\u0027";
    exports.UsernameCannotMatchPrimary = "Alternate secondary username cannot be the same as primary username";
});