// Copyright (C) Microsoft Corporation. All rights reserved.
define("Search/Package/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.ZeroPackageResultsMessageFormat = "No packages found for \u0027{0}\u0027 with applied filters";
    exports.ShowingXofYResultsTitle = "Showing {0} of {1} results";
    exports.ShowingXResultsTitle = "Showing {0} results";
    exports.SearchPackagePlaceholder = "Search package";
    exports.PackageWelcomeText = "Welcome to Package Search";
    exports.SearchPackageTitle = "Search package";
    exports.AllFeedsDisplayLabel = "All Feeds";
    exports.AllPackageTypesDisplayLabel = "All";
    exports.AllViewsDisplayLabel = "All";
    exports.FeedFilterCalloutContent = "The search term does not have a match in any feeds";
    exports.FindFeedPlaceholder = "Type to find a feed...";
    exports.FindPackageTypePlaceholder = "Type to find a package type...";
    exports.FeedsDisplayLabel = "Feeds";
    exports.PackageTypeDisplayLabel = "Type";
    exports.ShowingSingleFeed = "Showing 1 feed";
    exports.ShowingMultipleFeeds = "Showing {0} feeds";
    exports.FoundSingleFeed = "Found 1 feed";
    exports.FoundMultipleFeeds = "Found {0} feeds";
    exports.ShowingSingleView = "Showing 1 view";
    exports.ShowingMultipleViews = "Showing {0} views";
    exports.FoundSingleView = "Found 1 view";
    exports.FoundMultipleViews = "Found {0} views";
    exports.ShowingSingleType = "Showing 1 type";
    exports.ShowingMultipleTypes = "Showing {0} types";
    exports.FoundSingleType = "Found 1 type";
    exports.FoundMultipleTypes = "Found {0} types";
    exports.PackageTypeFilterCalloutContent = "The search term does not have a match in any package type";
    exports.ViewFilterCalloutContent = "Select one feed to filter by views in that feed";
    exports.ViewsDisplayLabel = "Views";
    exports.ViewDropdownPlaceholderText = "Type to find views...";
    exports.ZeroPackageResultsLearnMoreFormat = "{0} on Package search";
    exports.AritfactsSearchAriaLabel = "artifacts search";
    exports.ZeroPackageResultsWithoutFiltersMessageFormat = "No packages found for \u0027{0}\u0027";
    exports.PackageAriaLabel = "Package {0}";
    exports.ShowingPackageResultsFormat = "Showing {0} of {1} package results";
    exports.ShowingSinglePackageResult = "Showing 1 package result";
    exports.ShowingNPackageResultsFormat = "Showing {0} package results";
    exports.ZeroPackageResultsNoPermissionMessage = "You don\u0027t have permissions to access packages in this organization";
    exports.AccountIndexingMessage = "We are not able to show results because one or more feeds in your organization are still being indexed";
    exports.AccountIsGettingIndexedBannerMessage = "We are currently re-indexing one or more feeds. You may see partial search results.";
    exports.PackageProjectInputAriaLabel = "Search package in this project";
    exports.PackageOrgInputAriaLabel = "Search package in this organization";
});