// Copyright (C) Microsoft Corporation. All rights reserved.
define("VC/PullRequestList/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.MyPullRequests = "My pull requests";
    exports.PullRequestListCreatedByMe = "Created by me";
    exports.PullRequestListAssignedToMe = "Assigned to me";
    exports.PullRequestListAssignedToTeam = "Assigned to {0}";
    exports.EmptyPrListPrimary = "All clear!";
    exports.EmptyPrListSecondary = "No pull requests need your attention";
    exports.Draft = "Draft";
    exports.PRListSecondaryLine = "{0} request #{1} into {2} {3} {4} {5}";
    exports.PRListSecondaryLineMinimized = "{0} {1} {2} {3}";
    exports.RepositoryIconTitle = "Repository";
    exports.BranchIconTitle = "Branch";
    exports.ReviewerFullStatus = "{0} with status {1}";
    exports.ReviewersOverflowCountLabel = "+{0} other reviewers";
    exports.ReviewerGroupFullStatus = "{0} with status {1} via {2}";
    exports.DelegateReviewerTwoPeople = "{0} and 1 other";
    exports.DelegateReviewerThreePlusPeople = "{0} and {1} others";
    exports.DelegateReviewerViaFormat = "via {0}";
    exports.Approve = "Approved";
    exports.ApproveWithComment = "Approved with suggestions";
    exports.ReviewerFeedback_AwaitingResponse = "No response";
    exports.NotReady = "Waiting for the author";
    exports.Reject = "Rejected";
    exports.CommentsCount_MoreThanThreshold = "{0}+";
    exports.ZeroComments_Tooltip = "There are no comments in this pull request.";
    exports.OneComment_Tooltip = "There is 1 comment in this pull request.";
    exports.MultipleComments_Tooltip = "There are {0} comments in this pull request.";
    exports.Change_Singular = "{0} new change";
    exports.Change_Plural = "{0} new changes";
    exports.OtherChange_Singular = "{0} other change";
    exports.OtherChange_Plural = "{0} other changes";
    exports.New_Push_Singular = "{0} new push";
    exports.New_Push_Plural = "{0} new pushes";
    exports.New_Comment_Singular = "{0} new comment";
    exports.New_Comment_Plural = "{0} new comments";
    exports.New_Vote_Singular = "{0} new vote";
    exports.New_Vote_Plural = "{0} new votes";
    exports.New_Updates = "New updates";
    exports.Completed = "Completed {0}";
    exports.Abandoned = "Abandoned {0}";
    exports.Updated = "Updated {0}";
    exports.Created = "Created {0}";
    exports.CreatedBy = "Created by {0}";
    exports.Loading = "Loading...";
    exports.ShowMore = "Show more";
});