// Copyright (C) Microsoft Corporation. All rights reserved.
define("Work/Views/MyWork/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.MyWorkItems = "My work items";
    exports.NewWorkItem = "New work item";
    exports.MyProjects = "My projects";
    exports.NewProject = "New project";
    exports.AssignedToMe = "Assigned to me";
    exports.MyActivity = "My activity";
    exports.Following = "Following";
    exports.Mentioned = "Mentioned";
    exports.Loading = "Loading...";
    exports.WorkItemsSecondaryLine = "#{0} in {1}";
    exports.YouUpdatedDateFormat = "You updated {0}";
    exports.LastUpdatedDateFormat = "Updated {0}";
    exports.YouViewedDateFormat = "You viewed {0}";
    exports.LastMentionedDateFormat = "Mentioned {0}";
    exports.DiscoverProjects = "Discover projects";
    exports.ZeroData_LinkText = "Learn more about work items";
    exports.ZeroData_AssignedToMe_Primary = "Your work, all in one place";
    exports.ZeroData_AssignedToMe_Secondary = "Quickly take action on work items assigned to you.";
    exports.ZeroData_AssignedToMe_Link = "https://go.microsoft.com/fwlink/?linkid=831361";
    exports.ZeroData_Following_Primary = "Keep an eye on important work";
    exports.ZeroData_Following_Secondary = "Click {0} to get updates about the items you want to track.";
    exports.ZeroData_Following_LinkText = "Learn more about following";
    exports.ZeroData_Following_Link = "https:////go.microsoft.com//fwlink//?linkid=831363";
    exports.ZeroData_Following_NotConfigured_Primary = "Feature not supported";
    exports.ZeroData_Following_NotConfigured_Secondary = "Enable this feature to keep an eye on important work.";
    exports.ZeroData_Following_NotConfigured_LinkText = "Learn more about how to enable following";
    exports.ZeroData_Following_NotConfigured_Link = "https:////go.microsoft.com//fwlink//?linkid=831364";
    exports.ZeroData_Mentioned_Primary = "Don\u0027t miss important work";
    exports.ZeroData_Mentioned_Secondary = "Quickly take action on items where you have been @mentioned.";
    exports.ZeroData_Mentioned_LinkText = "Learn more about @mentions";
    exports.ZeroData_Mentioned_Link = "https:////go.microsoft.com//fwlink//?linkid=852411";
    exports.ZeroData_MyActivity_Primary = "Get back to your recent work";
    exports.ZeroData_MyActivity_Secondary = "Find work items you have recently opened or edited.";
    exports.ZeroData_MyActivity_Link = "https:////go.microsoft.com//fwlink//?linkid=831361";
    exports.General_Error = "A problem occurred when loading your work items.  Try refreshing the page.";
    exports.AssignedToMeQueryLimitExceeded = "There are more work items assigned to you than can be shown here.";
    exports.FollowsQueryLimitExceeded = "You follow more work items than can be shown on this page.";
});