// Copyright (C) Microsoft Corporation. All rights reserved.
define("Test/common-util/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.DayFormat = "{0}d";
    exports.HourFormat = "{0}h";
    exports.MinuteFormat = "{0}m";
    exports.SecondFormat = "{0}s";
    exports.MillisecondFormat = "{0}ms";
    exports.UnspecifiedText = "Unspecified";
    exports.AllText = "All";
    exports.PriorityText = "Priority";
    exports.NotAssociatedText = "NotAssociated";
    exports.TestOutcome_Result_Unspecified = "Unspecified";
    exports.TestOutcome_Passed = "Passed";
    exports.TestOutcome_Failed = "Failed";
    exports.TestOutcome_Others = "Others";
    exports.TestOutcome_None = "None";
    exports.TestOutcome_Inconclusive = "Inconclusive";
    exports.TestOutcome_Timeout = "Timeout";
    exports.TestOutcome_Aborted = "Aborted";
    exports.TestOutcome_PassedOnRerun = "Passed on rerun";
    exports.TestOutcome_Blocked = "Blocked";
    exports.TestOutcome_NotExecuted = "Not executed";
    exports.TestOutcome_Warning = "Warning";
    exports.TestOutcome_Error = "Error";
    exports.TestOutcome_NotApplicable = "Not Applicable";
    exports.TestOutcome_Paused = "Paused";
    exports.TestOutcome_InProgress = "In Progress";
    exports.TestOutcome_NotImpacted = "Not Impacted";
    exports.ResultOutcomeInfo = "{0} {1}";
    exports.ResultGridHeader_Duration = "Duration";
    exports.NotAvailableText = "not available";
    exports.ResultGridHeader_FailingRelease = "Failing release";
    exports.ResultGridHeader_FailingBuild = "Failing build";
    exports.ResultGridHeader_FailingSince = "Failing since";
    exports.ResultOutcomeAndMachineNameInfo = "{0} {1} on {2}";
    exports.Owner = "Owner";
    exports.DebugPivotLabel = "Debug";
    exports.CommentsText = "Comments";
    exports.ErrorMessageLabel = "Error message";
    exports.EnterFullScreenModeText = "Enter full screen mode";
    exports.ExitFullScreenModeText = "Exit full screen mode";
    exports.CloseDetailsPane = "Close test result details";
    exports.CloseOverlayPanel = "Close panel";
    exports.StackTraceLabel = "Stack trace";
    exports.WorkItemsText = "Work items";
    exports.AttachmentsHeaderText = "Attachments";
    exports.HistoryHeaderText = "History";
    exports.LoadingTestResultDetailsLabel = "Loading details...";
    exports.TagsText = "Tags";
});