// Copyright (C) Microsoft Corporation. All rights reserved.
define("WorkItemsHub/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.UnableToLoadHubData = "Unable to load data for this tab";
    exports.WorkItemsHubTitle = "Work Items";
    exports.WorkItemUnassigned = "Unassigned";
    exports.OpenInQueriesCommand = "Open in Queries";
    exports.CheckButtonLabel = "Select the row";
    exports.OpenSelectionInQueriesCommand = "Open selected items in Queries";
    exports.OpenFilteredInQueriesCommand = "Open filtered view in Queries";
    exports.KeyboardShortcutGroup_Work = "Work";
    exports.KeyboardShortcutGroup_WorkItems = "Work Items";
    exports.KeyboardShortcutDescription_ToggleFullScreen = "Toggle full screen mode";
    exports.CompletedItemsViewOptionName = "Completed Work Items";
    exports.CompletedItemsHidden = "Hidden";
    exports.CompletedItemsShown = "Shown";
    exports.SortAscendingText = "Ascending";
    exports.SortByLabel = "Sort by";
    exports.SortDescendingText = "Descending";
    exports.BackToWorkItems = "Back to Work Items";
    exports.TriageNextWorkItemTooltip = "Next work item in the \"{0}\" tab (Alt + N)";
    exports.TriagePreviousWorkItemTooltip = "Previous work item in the \"{0}\" tab (Alt + P)";
    exports.TriageBackToTabTooltip = "Back to \"{0}\" tab (Alt + Q)";
    exports.KeyboardShortcutDescription_BackToWorkItemsHub = "Back to Work Items";
    exports.CompletedWorkItemsOffText = "Completed work items hidden";
    exports.CompletedWorkItemsOnText = "Completed work items shown";
    exports.CompletedWorkItemsToggleLabel = "{0}. Press to toggle the completed work items option.";
    exports.FilterChangedAnnouncementFormat = "Filter has changed: {0}";
    exports.WorkItemsHubGridLandmarkLabel = "Work Items Hub grid";
    exports.ColumnOptions = "Column Options";
    exports.ActivityDateColumnDisplayName = "Activity Date";
    exports.MentionedDateColumnDisplayName = "Mentioned Date";
    exports.MyActivityDetailsColumnDisplayName = "Activity Details";
    exports.MyActivityDetailsUpdated = "Updated";
    exports.MyActivityDetailsViewed = "Viewed";
    exports.WorkItemsHubTruncatedCommentCount = "{0}+";
    exports.WorkItemsHubComments = "Comments";
    exports.CopySelectedWorkitemsOpenAsQuery = "Open as query";
    exports.CommandBarTitle_CopyWorkItems = "(Ctrl+C)";
    exports.CommandBarTitle_DeleteWorkItems = "(Del)";
    exports.CopiedContentDialogTitle = "Copied!";
    exports.EmailSelectedWorkItems = "Email...";
    exports.DeleteSelectedWorkItems = "Delete";
    exports.RecycleBin = "Recycle Bin";
    exports.CopyToClipboard = "Copy to clipboard";
    exports.Loading = "Loading...";
    exports.NewWorkItemButtonText = "New Work Item";
    exports.FilterByKeyword = "Filter by keyword";
    exports.FilterByTypes = "Types";
    exports.FilterNoTypes = "No types available";
    exports.FilterByStates = "States";
    exports.FilterNoStates = "No states available";
    exports.FilterByTags = "Tags";
    exports.FilterNoTags = "No tags available";
    exports.FilterByAreaPath = "Area";
    exports.FilterNoArea = "No areas available";
    exports.FilterByAssignedTo = "Assigned to";
    exports.FilterResults = "Filter results";
    exports.SelectAllAriaLabel = "Select all work items";
    exports.Illustrations_GetBackToRecentWorkAltText = "Get back to your recent work";
    exports.Illustrations_KeepAnEyeOnImportantWorkAltText = "Keep an eye on important work";
    exports.Illustrations_MentionSomeoneAltText = "Mention someone";
    exports.Illustrations_SomethingWrongOnServerAltText = "Server error";
    exports.Illustrations_YourWorkInOnePlaceAltText = "Your work, all in one place";
    exports.ZeroData_SecondaryMessageLinkText = "Learn more about work items";
    exports.ZeroData_AssignedToMe_PrimaryMessage = "Your work, all in one place";
    exports.ZeroData_AssignedToMe_SecondaryMessage = "Quickly take action on work items assigned to you.";
    exports.ZeroData_AssignedToMe_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=2010008";
    exports.ZeroData_Filter_WorkItems_ArtifactName = "work items";
    exports.ZeroData_Following_NotConfigured_PrimaryMessage = "Feature not supported";
    exports.ZeroData_Following_NotConfigured_SecondaryMessage = "Enable this feature to keep an eye on important work.";
    exports.ZeroData_Following_NotConfigured_SecondaryMessageLinkText = "Learn more about how to enable following";
    exports.ZeroData_Following_NotConfigured_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=2010112";
    exports.ZeroData_Following_PrimaryMessage = "Keep an eye on important work";
    exports.ZeroData_Following_SecondaryMessageFormat = "Click {0} to get updates about the items you want to track.";
    exports.ZeroData_Following_SecondaryMessageLinkText = "Learn more about following";
    exports.ZeroData_Following_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=2010009";
    exports.ZeroData_Mentioned_PrimaryMessage = "Don\u0027t miss important work";
    exports.ZeroData_Mentioned_SecondaryMessage = "Quickly take action on items where you have been @mentioned.";
    exports.ZeroData_Mentioned_SecondaryMessageLinkText = "Learn more about @mentions";
    exports.ZeroData_Mentioned_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=852411";
    exports.ZeroData_MyActivity_PrimaryMessage = "Get back to your recent work";
    exports.ZeroData_MyActivity_SecondaryMessage = "Find work items you have recently opened or edited.";
    exports.ZeroData_MyActivity_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=2010008";
    exports.ZeroData_RecentlyUpdated_PrimaryMessage = "Find recently updated items";
    exports.ZeroData_RecentlyUpdated_SecondaryMessage = "View items that have been recently updated.";
    exports.ZeroData_RecentlyUpdated_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=831361";
    exports.ZeroData_RecentlyCreated_PrimaryMessage = "Find recently created items";
    exports.ZeroData_RecentlyCreated_SecondaryMessage = "View items that are being created for this project.";
    exports.ZeroData_RecentlyCreated_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=831361";
    exports.ZeroData_ServerError_PrimaryText = "Server error";
    exports.ZeroData_RecentlyCompleted_PrimaryMessage = "Find recently completed items";
    exports.ZeroData_RecentlyCompleted_SecondaryMessage = "View items that are being completed for this project.";
    exports.ZeroData_RecentlyCompleted_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=831361";
    exports.ZeroData_MyTeams_PrimaryMessage = "Find what my team is working on";
    exports.ZeroData_MyTeams_SecondaryMessage = "View items from your team(s) that have been recently updated.";
    exports.ZeroData_MyTeams_SecondaryMessageLinkUrl = "https://go.microsoft.com/fwlink/?linkid=2010008";
    exports.ZeroData_MyTeams_NotConfigured_PrimaryMessage = "Feature not supported";
    exports.ZeroData_MyTeams_NotConfigured_SecondaryMessage = "You need to be a member of a team to find what your team is working on.";
    exports.GenericFilterZeroData_Message = "No {0} match your filter";
});