// Copyright (C) Microsoft Corporation. All rights reserved.
define("VC/Search/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.FilterByScope = "Filter by scope";
    exports.FilterByScopeExample = "(e.g., Activity ext:cs)";
    exports.ExtensionHint = "With file extension";
    exports.FilenameHint = "Filename";
    exports.PathHint = "Under path";
    exports.ProjectHint = "Inside project";
    exports.RepoHint = "Inside repository";
    exports.FilterByCodeType = "Filter by code type";
    exports.FilterByCodeTypeExample = "(e.g., ref:ApiRoot)";
    exports.ArgumentHint = "Argument";
    exports.BaseTypeHint = "Basetype";
    exports.CallerHint = "Caller";
    exports.ClassHint = "Class";
    exports.CDeclHint = "Class Declaration";
    exports.CDefHint = "Class Definition";
    exports.CommentHint = "Comment";
    exports.ConstructorHint = "Constructor";
    exports.DeclarationHint = "Declaration";
    exports.DefinitionHint = "Definition";
    exports.DestructorHint = "Destructor";
    exports.EnumHint = "Enumeration";
    exports.ExternHint = "Extern";
    exports.FieldHint = "Field";
    exports.FriendHint = "Friend";
    exports.FuncHint = "Function";
    exports.FuncDeclHint = "Function Declaration";
    exports.FuncDefHint = "Function Definition";
    exports.GlobalHint = "Global";
    exports.HeaderHint = "Header";
    exports.InterfaceHint = "Interface";
    exports.MacroHint = "Macro";
    exports.MacroDefHint = "Macro Definition";
    exports.MacroRefHint = "Macro Reference";
    exports.MethodHint = "Method";
    exports.MethodDeclHint = "Method Declaration";
    exports.MethodDefHint = "Method Definition";
    exports.NamespaceHint = "Namespace";
    exports.PropertyHint = "Property";
    exports.ReferenceHint = "Reference";
    exports.StringLitHint = "String Literal";
    exports.StructHint = "Struct";
    exports.StructDeclHint = "Struct Declaration";
    exports.StructDefHint = "Struct Definition";
    exports.TemplateArgHint = "Template Argument";
    exports.TemplateSpecHint = "Template Specification";
    exports.TypeHint = "Type";
    exports.TypeDefHint = "Type Definition";
    exports.UnionHint = "Union";
    exports.Operators = "Operators";
    exports.OperatorsExample = "Operators Example";
});