// Copyright (C) Microsoft Corporation. All rights reserved.
define("Build/Queue-Panel/Resources", ["require", "exports"], function (require, exports) {
    "use strict";
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.AddDemandButton = "Add demand";
    exports.AddDemandPanelTitle = "New demand";
    exports.AddVariableButton = "Add variable";
    exports.AddVariablePanelTitle = "New variable";
    exports.AgentPool = "Agent pool";
    exports.BranchLabel = "Branch/tag";
    exports.BuildQueuedMessage = "Build #{0} has been queued.";
    exports.CancelButtonText = "Cancel";
    exports.CloseButtonAriaLabel = "Close";
    exports.ConditionFieldLabel = "Condition";
    exports.CreateButtonText = "Create";
    exports.DeleteButtonEmptyTooltip = "Delete variable";
    exports.DeleteButtonTooltip = "Delete variable \u0027{0}\u0027";
    exports.DemandsTabTitle = "Demands";
    exports.DuplicateVariableMessage = "Variable \u0027{0}\u0027 is already defined";
    exports.EmptyDemandsDescription = "You can add demands for this run.";
    exports.EmptyDemandsVariablesLink = " Learn more.";
    exports.EmptyVariablesDescription = "You can add variables for this run.";
    exports.EqualsCondition = "equals";
    exports.ExistsCondition = "exists";
    exports.GitSourceSelectorDescription = "select the branch or commit tag";
    exports.NameFieldLabel = "Name";
    exports.QueueButtonText = "Run";
    exports.QueuePanelDescription = "Select parameters below and manually run the pipeline";
    exports.QueuePanelTitleNoDefinition = "Run pipeline";
    exports.RunWithDiagnostics = "Enable system diagnostics";
    exports.RunWithWarningsButtonText = "Run anyway";
    exports.SaveAndRunWithWarningsButtonText = "Save and run anyway";
    exports.SaveAndQueueButtonText = "Save and run";
    exports.SaveComment = "Save comment";
    exports.SecretFieldLabel = "Keep this value secret";
    exports.SecretValue = "secret";
    exports.SourceVersionLabel = "Source version";
    exports.StartingRun = "Starting run...";
    exports.TfsGitSourceSelectorDescription = "Select the branch, commit or commit tag";
    exports.UpdateButtonText = "Update";
    exports.UpdateDemandPanelTitle = "Update demand";
    exports.UpdateVariablePanelTitle = "Update variable";
    exports.ValueFieldLabel = "Value";
    exports.VariableRequiredNameMessage = "Variable name is required";
    exports.VariablesTabTitle = "Variables";
});